# This file configures the hello-world app which serves public web traffic.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: hello
      tier: frontend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
        track: stable
    spec:
      containers:
        - name: hello
          image: "gcr.io/my-project-64131-terraform/hello-app:1.0"
